[build]
  publish = "public"
  command = """
  SASS_DIR="$HOME/.local/dart-sass"
  VERSION="${DART_SASS_VERSION:-1.73.1}"
  if [ ! -d "$SASS_DIR" ]; then
    echo "Download Dart Sass $VERSION..."
    curl -sLJO "https://github.com/sass/dart-sass/releases/download/$VERSION/dart-sass-$VERSION-linux-x64.tar.gz"
    mkdir -p "$HOME/.local"
    tar -C "$HOME/.local" -xf "dart-sass-$VERSION-linux-x64.tar.gz"
    rm "dart-sass-$VERSION-linux-x64.tar.gz"
  fi
  export PATH="$SASS_DIR:$PATH"
  git config core.quotepath false
  hugo --gc --minify --baseURL "$URL"
  """

[build.environment]
  DART_SASS_VERSION = "1.93.2"
  HUGO_VERSION = "0.152.2"
  HUGO_EXTENDED = "true"
  GO_VERSION = "1.25.5"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".local/dart-sass"]
